# SVN ID: $Id$

all:    mrvoice.pdf

mrvoice.pdf :  $(CHAPTERS)
	docbook2pdf ../sgml/$(BOOK).sgml
#	openjade -t tex -d $(PDF_STYLESHEET) -o $(BOOK).tex -V nochunks ../sgml/$(BOOK).sgml
#	pdfjadetex $(BOOK).tex
#	pdfjadetex $(BOOK).tex
#	pdfjadetex $(BOOK).tex
