# CVS ID: $Id: Makefile,v 1.2 2002/04/17 01:57:47 minter Exp $

all:    mrvoice.pdf

mrvoice.pdf :  $(CHAPTERS)
	docbook2pdf ../sgml/$(BOOK).sgml
#	openjade -t tex -d $(PDF_STYLESHEET) -o $(BOOK).tex -V nochunks ../sgml/$(BOOK).sgml
#	pdfjadetex $(BOOK).tex
#	pdfjadetex $(BOOK).tex
#	pdfjadetex $(BOOK).tex
